# This file defines the Gitpod configuration for the Terraform Beginner Bootcamp 2023 project.

# The `tasks` section defines a list of tasks that will be executed when the workspace is started.
tasks:
  # The `terraform` task installs the Terraform CLI by running the `install_terraform_cli` script.
  - name: terraform
    before: |
      source ./bin/install_terraform_cli

  # The `aws-cli` task installs the AWS CLI and sets the `AWS_CLI_AUTO_PROMPT` environment variable to `on-partial`.
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli

# The `vscode` section defines the list of VS Code extensions that will be installed in the workspace.
vscode:
  extensions:
    # The `aws-toolkit-vscode` extension provides AWS-specific functionality for VS Code.
    - amazonwebservices.aws-toolkit-vscode

    # The `terraform` extension provides Terraform-specific functionality for VS Code.
    - hashicorp.terraform